function decodebit=turbodecode(demod,intrlvrIndices)
hTDec = comm.TurboDecoder('TrellisStructure',poly2trellis(4, ...
    [13 15 17],13),'InterleaverIndices',intrlvrIndices, ...
    'NumIterations',4);
decodebit=step(hTDec,demod);